name: Lint & Test

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

env:
  GO_VERSION: "1.21"

jobs:
  # 린트 및 정적 분석
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true
          cache-dependency-path: go.sum

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
          args: --timeout=5m

  # 테스트 요약
  test-summary:
    name: Test Summary
    runs-on: ubuntu-latest
    needs: [lint]
    if: always()

    steps:
      - name: Check test results
        run: |
          echo "Lint: ${{ needs.lint.result }}"

          if [[ "${{ needs.lint.result }}" != "success" ]]; then
            echo "::error::One or more required jobs failed"
            exit 1
          fi

      - name: Create test summary
        run: |
          echo "# Test Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Job | Status |" >> $GITHUB_STEP_SUMMARY
          echo "|-----|--------|" >> $GITHUB_STEP_SUMMARY
          echo "| Lint | ${{ needs.lint.result }} |" >> $GITHUB_STEP_SUMMARY
